# --- !Ups

CREATE TABLE TProducts (
 "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 "TITLE" TEXT  NOT NULL,
 "AUTHOR" TEXT NOT NULL,
 "CATEGORYID" INTEGER NOT NULL,
 "PRICE" INTEGER NOT NULL,
 FOREIGN KEY(CATEGORYID) REFERENCES TCategory(ID)
);

CREATE TABLE TCartItem (
 "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
 "PRODUCTID" INTEGER NOT NULL,
 "ORDERID" INTEGER NOT NULL,
 "AMOUNT" INTEGER NOT NULL,
 FOREIGN KEY(ORDERID) REFERENCES TOrders(ID),
 FOREIGN KEY(PRODUCTID) REFERENCES TProducts(ID)
);

CREATE TABLE TOrders (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "TOTALAMOUNT" INTEGER NOT NULL,
  "SHIPMENT" TEXT NOT NULL,
  "PAYMENT" TEXT NOT NULL
);

CREATE TABLE TCategory (
  "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "NAME" TEXT NOT NULL
);

# --- !Downs

DROP TABLE IF EXISTS TProducts;
DROP TABLE IF EXISTS TCartItem;
DROP TABLE IF EXISTS TOrders;
DROP TABLE IF EXISTS TCategory;